services:

  # Tokenization Frontend
  tokenization-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_OVERLAY_URL=https://store-us-1.bsvb.tech
    container_name: tokenization-frontend
    ports:
      - "8080:8080"
    restart: unless-stopped
